development:
  adapter: postgresql
  encoding: unicode
  database: directory_scraper_db
  pool: 2
  username: noahschechter
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: directory_scraper_db
  pool: 2
  username: noahschechter
  password: password